### ISSUE TITLE
一个测试时候的bug

### ISSUE THREAD

**Issue by han48614284** [wcy-cs/SFMNet#10]
(SFMNet) gpu@gpu:/media/gpu/HS/SFMNet$ python test.py --model MYNET --load /media/gpu/HS/SFMNet/weight/SFMNet_x4.pth  --data_path /media/gpu/HS/SFMNet/testset/LR_x4_CelebA/ --save_name name
/media/gpu/HS/SFMNet/testset/LR_x4_CelebA/test/LR_bicubic /media/gpu/HS/SFMNet/testset/LR_x4_CelebA/test/HR
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    eval_model(model, testset1, args.save_name, 0, args)
  File "test.py", line 37, in eval_model
    psnr_c, ssim_c = torch_psnr(data['img_gt'], sr['img_out'])
  File "/media/gpu/HS/SFMNet/utils/metric.py", line 57, in torch_psnr
    sum_psnr.append(calc_psnr(rgb2ycbcr(img_pred[i]), rgb2ycbcr(img_gt[i])))
  File "/media/gpu/HS/SFMNet/utils/metric.py", line 20, in calc_psnr
    mse = np.mean((img1_np - img2_np)**2)
ValueError: operands could not be broadcast together with shapes (112,112) (16,16)
你好，请问这个错误是因为啥出现的？

**Comment by wcy-cs** [comment]
你好，这个应该是因为sr和hr分辨率不一样，本文方法在推理前把LR插值成跟hr一样大小的，然后在送进去超分。

**Comment by han48614284** [comment]
好的，谢谢！> 你好，这个应该是因为sr和hr分辨率不一样，本文方法在推理前把LR插值成跟hr一样大小的，然后在送进去超分。

**Comment by wcy-cs** [comment]
不客气
