### ISSUE TITLE
test with 256x256 images and possibility to adapt SFMNet to much higher resolutions ?

### ISSUE THREAD

**Issue by BeauGeogeo** [wcy-cs/SFMNet#11]
Hi, thanks for sharing great work !

I've been able to modify a bit your code in order to test with my custom images. At first I did not understand why the images I got were degraded and that their resolution was not higher, but after reading the paper I understood that your LR images are really low and the HR images are 128x128, right ?

Therefore I have 2 questions :

1/ I think your code can "handle" larger resolution images thanks to convolution which can work with different input format, right ?

2/ Do you think it is easily feasible to adapt and train your model to go from 256x256 to 512x512 or even 1024x1024 resolution or would it take too much time ? I don't see how it can scale in terms of complexity.

Thanks a lot

Geoffrey

**Comment by wcy-cs** [comment]
Hi, our model is trained for x4 and x8 face super-resolution (32x32->128x128, 16x16->128x128).
1) Maybe. I  am not sure.
2) In our experiments, we train our model on more 160,000 face images (128x128) in about 1.5 hours. However, i have not trained it on 256x256 or 1024x1024, I think it will have high memory requirements.

**Comment by BeauGeogeo** [comment]
Hello.

Alright thank you very much for your answer. I'll try to adapt your framework to perform super resolution with higher dimensional LR and HR images. The techniques in the paper are really good and interesting and I've seen some other recent papers drawing on similar ideas and achieving great results in super resolution or other challenging and related CV tasks.

Thanks again !

**Comment by wcy-cs** [comment]
Thank you for your attention!
