### ISSUE TITLE
The input images’ size must be 128*128？

### ISSUE THREAD

**Issue by haohena** [wcy-cs/SFMNet#14]
Thanks for your work！It impresses me so much。But i have a question about the input size，when i run test.py，i found that the input and output images  were 16*16 while the HR images were 128*128，the psnr couldn‘t be calculated。
Is there a upsample that make the input 16*16 resize into 128*128？

**Comment by wcy-cs** [comment]
We use bicubic to upsample the LR from 16x16 to 128x128, and then feed it into the network. Thank you for your attention.

**Comment by cs-hao** [comment]
> We use bicubic to upsample the LR from 16x16 to 128x128, and then feed it into the network. Thank you for your attention.

作者，我并没有见到你在哪一步进行了bicubic 上采样呀？你提供的测试集都是降采样的，并没有提供降采样之后再bicubic上采样的，代码中也没有呢。

**Comment by cs-hao** [comment]
> 您好，我稍后会提供一个插值后的，感谢提醒。

其实作者为什么不直接在dataset.py里面使用python代码进行上下采样呢？

**Comment by wcy-cs** [comment]
哈哈 提醒我了，当时是处理好数据后跑模型的，加在dataset里面应该也可以，我去更新一下。
