### ISSUE TITLE
The concrete number about epochs

### ISSUE THREAD

**Issue by haohena** [wcy-cs/SFMNet#15]
您好，我想在您的项目中训练自己的数据，我想参考您在psnr阶段训练了多少epoch，以及gan模式下具体训练了多少epoch，1000和400吗，而且我在训练时训练速度很慢，不知您在训练时是否也有这样的情况

**Comment by wcy-cs** [comment]
您好，我当时在128x128(168854张)人脸数据集上训练一个epoch大概是1.5小时，在PSNR阶段是训练了大概50个epoch，在GAN模式调整的时候10个epoch。
