### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by haohena** [wcy-cs/SFMNet#16]
您好，我们使用openface的outerEyesAndNose方法裁剪获得19万张人脸在您的项目中按照相关超参数进行训练，训练结果不是很理想，会是数据集的问题吗，如果是能麻烦您分享一下您使用的训练数据吗，如果不是，希望您能够给出相关指导建议，非常感谢！

**Comment by wcy-cs** [comment]
您好，您说的这个数据集问题，我不太确定，但是我可以给您提供我们的训练数据。链接: https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg 提取码: nb2s 
您可以试下。
