### ISSUE TITLE
代码问题关于傅里叶变换

### ISSUE THREAD

**Issue by lanyingyuexi** [wcy-cs/SFMNet#19]
您好，请问运行程序时报错AttributeError: 'builtin_function_or_method' object has no attribute 'rfft2'可以定位到File "/SFMNet/models/common.py", line 195, in forward   msF = torch.fft.rfft2(self.fpre(x) + 1e-8, norm = "backword") 。查找了很久没找到解决办法，请问您有遇到这个问题吗？需要怎么解决呢，感谢

**Comment by wcy-cs** [comment]
您好，应该是pytorch版本问题， 使用torch 1.12.0应该就可以

**Comment by lanyingyuexi** [comment]
> 您好，应该是pytorch版本问题， 使用torch 1.12.0应该就可以

换成您说的版本可以了，感谢
