### ISSUE TITLE
视觉效果图的对比方法复现困难

### ISSUE THREAD

**Issue by haohena** [wcy-cs/SFMNet#20]
感谢您的耐心答复，当我们进行视觉效果图对比时，我们从对比方法的github下下载源码进行调试运行自己的测试集进行对比，但是复现调试十分困难，不知您是否有简单一些的方法可以查看到对比方法在测试集上的视觉效果图。

**Comment by wcy-cs** [comment]
您好，我没理解您的意思，是说对比方法（而不是我们的方法）调试困难嘛？您说的测试集视觉效果图是指我们这篇论文的测试集其他方法的结果嘛？

**Comment by wcy-cs** [comment]
您好，这个有点记不太清了，但是如果需要的话，我可以提供这两个方法在我们的测试集上的结果。

**Comment by haohena** [comment]
好的，希望能获得您的相关测试结果，将会对我们工作有很大参考价值

**Comment by wcy-cs** [comment]
您好，测试结果百度网盘链接: https://pan.baidu.com/s/1pKj_FYGWLHirOl4XceSrww 提取码: pw66

**Comment by duweihua** [comment]
> 您好，测试结果百度网盘链接: https://pan.baidu.com/s/1pKj_FYGWLHirOl4XceSrww 提取码: pw66
您好，这个链接失效了同时想问下是否能提供制作的训练数据集？

**Comment by wcy-cs** [comment]
您好，训练数据链接：https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg 提取码: nb2s

**Comment by duweihua** [comment]
> 您好，训练数据链接：https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg 提取码: nb2s
Trank you very much!
