### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by yeager415** [wcy-cs/SFMNet#21]
您好，请问我按照这样的指令 python test.py --model MYNET --load SFMGAN_x8.pth  --data_path LR_x8_helen\LR --save_name result
结果提示 File "D:\GitHubrepo\SFMNet-main\test.py", line 44, in eval_model
    print("Epoch：{}, {}, psnr: {:.3f}".format(epoch+1, name, val_psnr_dic/(len(dataset))))
ZeroDivisionError: division by zero
是为什么呢

**Comment by wcy-cs** [comment]
您好，这个看起来应该是数据集读取失败，当前这个test代码它是需要读取成对的LR和HR的, data_path的参数需要是一个文件夹，文件夹中LR_bicubic和HR两个子文件夹分别包括低分辨率和高分辨率人脸图像。
