### ISSUE TITLE
指标LPIPS如何得到

### ISSUE THREAD

**Issue by xcwqaq999** [wcy-cs/SFMNet#22]
亲爱的作者，您好，非常感谢您精彩的工作，我在复现代码的过程中，并没有在您的代码中看见LPIPS的计算代码，方便提供一下LPIPS的计算代码么

**Comment by wcy-cs** [comment]
您好，相关代码已更新。

**Comment by Greatxcw** [comment]
谢谢，非常感谢您精彩的工作！
