### ISSUE TITLE
关于mynet.py中前向传播的一些问题

### ISSUE THREAD

**Issue by ivcagcowkh** [wcy-cs/SFMNet#23]
作者您好！请问在mynet.py定义的前向传播中， 以下这两个语句x_fre = self.head_fre(sample["lr_up"])和x = self.head(sample["lr_up"])，这个lr_up是怎么来的呢？输入的时候LR不是叫“LR_bibubic”吗？

**Comment by wcy-cs** [comment]
您好，您可以看一下dataset.py

**Comment by xcwqaq999** [comment]
谢谢，非常感谢您精彩的工作！
