### ISSUE TITLE
关于对比算法中的SRCNN模型无法复现出类似的性能

### ISSUE THREAD

**Issue by ivcagcowkh** [wcy-cs/SFMNet#24]
作者您好，在对比算法中，我试了一下SRCNN在同样的CelebA训练集（168854张图像）进行训练，x4的SRCNN训练后得到的最好的PSNR是27.83，而您文中得到的结果是28.04，请问您是怎么做的呢？可以麻烦说一下吗，十分感谢!

**Comment by wcy-cs** [comment]
您好，您看下psnr计算方法是否和本文的一样呢？

**Comment by ivcagcowkh** [comment]
好的我试试

**Comment by amazingwmq** [comment]
您好，方便共享一下训练数据吗，不太了解具体的细节。

**Comment by wcy-cs** [comment]
您好，训练数据。链接: https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg 提取码: nb2s

**Comment by amazingwmq** [comment]
谢谢作者！
