### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by amazingwmq** [wcy-cs/SFMNet#25]
我非常赞赏您在论文中提出的将空间域和频率域信息结合的创新方法，尤其是SFML框架的设计和实现给了我很多启发。在复现过程中，我对其中的一些设置有一些疑问：
1、请问作者在训练的时候使用的数据集CelebA，只是用了168,854张，是随机选择其中的这么多张图像吗？
2、使用OpenFace来提取68个facial landmarks是要以什么方式输入呢？
3、训练时候对应的LR是怎么生成的呢？

**Comment by wcy-cs** [comment]
您好，关于问题1：CelebA数据的设置，我们是遵从的DIC的设置，详细细节可参考DIC (Deep Iterative Collaboration for Face Super-Resolution)；关于问题2：我没太懂“什么方式输入”是什么意思，我们在做的时候是读取图片，然后检测关键点，然后再裁剪，这个的详细部分也可以参考DIC的代码；关于问题3：训练的时候的LR是由HR下采样4 8 16倍得到。用openface检测了关键点，然后根据关键点对人脸图像进行裁剪成128x128就可以得到HR。

**Comment by amazingwmq** [comment]
非常感谢作者的耐心解释，我会根据您的指导下去好好看一下的！
