### ISSUE TITLE
資料集問題

### ISSUE THREAD

**Issue by Inthedarkz** [wcy-cs/SFMNet#27]
作者你好

最近我想嘗試看看SFMNet的部份, 但在資料集方面因為我沒有百度網盤的部份, 有其他方式可以取得你提供的資料集嗎？ 謝謝

**Comment by wcy-cs** [comment]
您好，没太懂您的意思，是看SFMNet的哪些部分呢？

**Comment by Inthedarkz** [comment]
在Test dataset的部分，由於我沒有百度網盤，在申請上也無法收到簡訊所以想請問是否有其他方法可以取得您提供的資料集 謝謝

**Comment by wcy-cs** [comment]
您好，我已将测试集上传到谷歌云盘，您可以在这里下载测试集：[
](https://drive.google.com/drive/folders/1fLuenH_weLy5KTe0PT99BTsK2uYdkmGg?usp=sharing)

**Comment by wcy-cs** [comment]
https://drive.google.com/drive/folders/1fLuenH_weLy5KTe0PT99BTsK2uYdkmGg?usp=sharing
