### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wzylove** [wcy-cs/SFMNet#28]
Hello author, I would like to ask if your dataset is celebA. Is it incomplete? It seems that the dataset contains a total of 202599 images. Do you have a complete dataset that you can provide to me?

**Comment by wcy-cs** [comment]
Hello, the dataset in our paper is CelebA. Following DIC (https://github.com/Maclory/Deep-Iterative-Collaboration) , we use 168854 images for training and 1000 images for testing. You can download the whole celebA from the official website of CelebA(https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html).
