### ISSUE TITLE
能不能放一下数据集列表和文件放的目录位置

### ISSUE THREAD

**Issue by Guohaitao1** [wcy-cs/SFMNet#29]

**Comment by wcy-cs** [comment]
不太懂您的意思，代码中的data_path 用于指定数据的根目录，data_train, data_val data_test分别指定训练、验证和测试的数据路径。关于数据集列表：在训练、验证和测试文件夹中均有HR(高分辨率图像)、LR_bicubic(8倍低分辨率人脸图像)、LR_x4_bicubic(4倍低分辨率人脸图像)、LR_x16_bicubic(16倍低分辨率人脸图像)。
