### ISSUE TITLE
测试的时候图片处理

### ISSUE THREAD

**Issue by lihuining** [wcy-cs/SFMNet#4]
你好，文章里面提到测试的时候从Helen数据集当中选取了50张图片，这些图片除了缩放到128*128还有其他的处理操作吗？我这里直接用的训练好的模型SFMNet_x4.pth，然后随机选了一部分Helen，但是得到的结果很奇怪，这些人脸扭曲非常严重，不知道是哪里设置的问题？
![232194_1](https://github.com/wcy-cs/SFMNet/assets/69829672/92b8a4df-6001-459f-820d-761b12dedd2f)
![11329920_1](https://github.com/wcy-cs/SFMNet/assets/69829672/9defc38e-a28a-4a3b-8478-e7c7d3d5f15b)

![18467619_1](https://github.com/wcy-cs/SFMNet/assets/69829672/21b4a439-c507-49f8-8a6f-3b3acd4bd3fe)

**Comment by wcy-cs** [comment]
你好，我们是先检测landmark，然后根据landmark对图像进行对齐、裁剪、下采样，得到的低分辨率图像，我已把测试集数据放在项目里。

**Comment by laodar** [comment]
> 
你好具體是怎麼預處理的呢，我需要測試自己的數據

**Comment by wcy-cs** [comment]
你好，我没太懂你的意思，是说有低分辨率测试图，然后怎么用预训练的模型推理出结果吗？

**Comment by laodar** [comment]
@wcy-cs 不好意思，没怎么说清楚。我直接用其他算法切出来的低分辨率人脸测试效果不理想，想知道你这边具体是怎么切出人脸的。

**Comment by wcy-cs** [comment]
@laodar 你好，我切出来人脸的方法主要是先用dlib检测landmark，然后用DIC(https://github.com/Maclory/Deep-Iterative-Collaboration)的数据部分代码，把人脸裁剪出来的。具体的代码，我一时没找到，可以参考下DIC的数据部分代码。

**Comment by laodar** [comment]
> 

@wcy-cs 好的多谢，我先试试。以后找到了麻烦通知一下哈哈哈

**Comment by wcy-cs** [comment]
@laodar 好的，没问题嘿嘿
