### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by zhenyuan1234** [wcy-cs/SFMNet#5]
你好，找不见models以及models.get_model
import models
def get_parameter_number(net):
    total_num = sum(p.numel() for p in net.parameters())
    trainable_num = sum(p.numel() for p in net.parameters() if p.requires_grad)
    return {'Total': total_num, 'Trainable': trainable_num}

args.epoch = 1000
epochs = args.epochs
model = models.get_model(args)

**Comment by wcy-cs** [comment]
你好，我更新了项目，可以重新下载，也可以在本地把model文件夹改成models，就可以了。
