### ISSUE TITLE
您好，论文中的图1应该如何绘制？

### ISSUE THREAD

**Issue by chenjiachengzzz** [wcy-cs/SFMNet#7]

**Comment by wcy-cs** [comment]
您好，论文中的图1，就是展示的图像的振幅、相位、以及从二者重建出来的图像。首先将图像进行傅里叶变换，得到振幅和相位，然后展示出来就可以了。至于从二者重建出来的图像，我们只需要将另一部分用常数代替，然后用逆傅里叶变换重建出来图像就可以了。比如要展示从相位重建出来的图像，我就将振幅用常数替代，然后从相位和替代后的振幅逆傅里叶变换成图像。

**Comment by chenjiachengzzz** [comment]
> 您好，论文中的图1，就是展示的图像的振幅、相位、以及从二者重建出来的图像。首先将图像进行傅里叶变换，得到振幅和相位，然后展示出来就可以了。至于从二者重建出来的图像，我们只需要将另一部分用常数代替，然后用逆傅里叶变换重建出来图像就可以了。比如要展示从相位重建出来的图像，我就将振幅用常数替代，然后从相位和替代后的振幅逆傅里叶变换成图像。

首先非常感谢您的耐心解答，您的工作也非常启发我。按照您提供的思路，我尝试绘制，但是遇到了一些问题，您能否分享给我相关绘制图1的代码！

**Comment by wcy-cs** [comment]
您好，我刚找了一下，没找到，不好意思。您可以参考一下其他用傅里叶变换的方法，或者网上有些相关代码。

**Comment by chenjiachengzzz** [comment]
> 您好，我刚找了一下，没找到，不好意思。您可以参考一下其他用傅里叶变换的方法，或者网上有些相关代码。

好的，我在找一些别的方法，十分感谢您的耐心回复！
