### ISSUE TITLE
a bug in  main_two.py

### ISSUE THREAD

**Issue by ChassWind** [wcy-cs/SFMNet#9]
如果我没理解错的话，在eval_model方法中存在bug,filename在使用前并没有得到赋值，且逻辑上存在问题，训练和测试时使用的batch_size为同样的值，会导致模型在测试图片时只会保留每个batch的第一张图片。

**Comment by wcy-cs** [comment]
你好，感谢提醒。我已经更新了main_two相关代码。实际上我们在训练时是不需要保存测试结果，不使用filename。我已经注释掉了保存图像的代码。谢谢！
